<?php

// [ Update Your Values In Line No 19 and 20 Acces Token and Autorization ]
// URL also May Be Get Change 🥱😆 
// (c) @AviPatilPro GitHub

$curl = curl_init();
$channel =$_GET['c'];

$url="https://spapi.zee5.com/singlePlayback/getDetails/secure?channel_id=$channel&device_id=x4cv34IfxXPxRQuqF7tU000000000000&platform_name=desktop_web&translation=en&user_language=en,hi,pa&country=IN&state=DL&app_version=2.51.73&user_type=premium&check_parental_control=false&gender=Male&uid=b2b2be24-6b48-4e2b-a490-7149e6f49c6c&ppid=x4cv34IfxXPxRQuqF7tU000000000000&version=12";
curl_setopt_array($curl, array(
  CURLOPT_URL => $url,
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS =>'{
  "x-access-token": "eyJ0eXAiOiJqd3QiLCJhbGciOiJIUzI1NiJ9.eyJwcm9kdWN0X2NvZGUiOiJ6ZWU1QDk3NSIsInBsYXRmb3JtX2NvZGUiOiJXZWJAJCF0Mzg3MTIiLCJpc3N1ZWRBdCI6IjIwMjItMDctMDhUMDY6MzA6MDIrMDAwMCIsInR0bCI6ODY0MDB9.0h51mjEIor1RclRj0vgGGaSB3v1Vmdz0bbzwRybm7Ww",    
  "Authorization": "bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2NTcyNjM2MTYsImV4cCI6MTY4ODc5OTYxNiwiaXNzIjoiaHR0cHM6Ly91c2VyYXBpLnplZTUuY29tIiwiYXVkIjpbImh0dHBzOi8vdXNlcmFwaS56ZWU1LmNvbS9yZXNvdXJjZXMiLCJzdWJzY3JpcHRpb25hcGkiLCJ1c2VyYXBpIl0sImNsaWVudF9pZCI6InJlZnJlc2hfdG9rZW5fY2xpZW50Iiwic3ViIjoiYjJiMmJlMjQtNmI0OC00ZTJiLWE0OTAtNzE0OWU2ZjQ5YzZjIiwiYXV0aF90aW1lIjoxNjU3MjYzNjE2LCJpZHAiOiJsb2NhbCIsInVzZXJfaWQiOiJiMmIyYmUyNC02YjQ4LTRlMmItYTQ5MC03MTQ5ZTZmNDljNmMiLCJzeXN0ZW0iOiJaNSIsImFjdGl2YXRpb25fZGF0ZSI6IjIwMjItMDUtMThUMTE6NTY6MTQiLCJjcmVhdGVkX2RhdGUiOiIyMDIwLTExLTIyVDA2OjUyOjE3IiwicmVnaXN0cmF0aW9uX2NvdW50cnkiOiJJTiIsInVzZXJfZW1haWwiOiJwYXZhbmt1bWFyLnlkQGdtYWlsLmNvbSIsInN1YnNjcmlwdGlvbnMiOiJbe1wiaWRcIjpcIjZhY2E1Yjc5LWEyNzQtNGQ5OS1hZmU4LTRmZDBjYWQ2M2RiNlwiLFwidXNlcl9pZFwiOlwiYjJiMmJlMjQtNmI0OC00ZTJiLWE0OTAtNzE0OWU2ZjQ5YzZjXCIsXCJpZGVudGlmaWVyXCI6XCJDUk1cIixcInN1YnNjcmlwdGlvbl9wbGFuXCI6e1wiaWRcIjpcIjAtMTEtMTg0MlwiLFwiYXNzZXRfdHlwZVwiOjExLFwic3Vic2NyaXB0aW9uX3BsYW5fdHlwZVwiOlwiU1ZPRFwiLFwidGl0bGVcIjpcIlByZW1pdW1cIixcIm9yaWdpbmFsX3RpdGxlXCI6XCJQcmVtaXVtXCIsXCJzeXN0ZW1cIjpcIlo1XCIsXCJkZXNjcmlwdGlvblwiOlwiNTAlIG9mZiBvbiDigrk5OTlcIixcImJpbGxpbmdfY3ljbGVfdHlwZVwiOlwiZGF5c1wiLFwiYmlsbGluZ19mcmVxdWVuY3lcIjozNjUsXCJwcmljZVwiOjQ5OS4wLFwiY3VycmVuY3lcIjpcIklOUlwiLFwiY291bnRyeVwiOlwiSU5cIixcImNvdW50cmllc1wiOltcIklOXCJdLFwic3RhcnRcIjpcIjIwMjEtMDItMTJUMDA6MDA6MDBaXCIsXCJlbmRcIjpcIjIwMjItMDMtMTNUMjM6NTk6NTlaXCIsXCJvbmx5X2F2YWlsYWJsZV93aXRoX3Byb21vdGlvblwiOnRydWUsXCJyZWN1cnJpbmdcIjpmYWxzZSxcInBheW1lbnRfcHJvdmlkZXJzXCI6W3tcIm5hbWVcIjpcIkFtYXpvbklBUFwiLFwicHJvZHVjdF9yZWZlcmVuY2VcIjpcInplZTVfb2ZmZXJfcGFja19pbl8xeVwifSx7XCJuYW1lXCI6XCJRd2lrY2lsdmVyXCJ9LHtcIm5hbWVcIjpcIlBheVRNXCJ9LHtcIm5hbWVcIjpcIkp1c1BheVwifSx7XCJuYW1lXCI6XCJQYXlVXCJ9LHtcIm5hbWVcIjpcIlBheXRtUVJcIn0se1wibmFtZVwiOlwiUGF5dG1RUlVQSVwifV0sXCJwcm9tb3Rpb25zXCI6W10sXCJhc3NldF90eXBlc1wiOls2LDAsOV0sXCJhc3NldF9pZHNcIjpbXSxcImJ1c2luZXNzX3R5cGVcIjpcImZyZWVcIixcImJpbGxpbmdfdHlwZVwiOlwicHJlbWl1bVwiLFwibnVtYmVyX29mX3N1cHBvcnRlZF9kZXZpY2VzXCI6MyxcIm1vdmllX2F1ZGlvX2xhbmd1YWdlc1wiOltdLFwidHZfc2hvd19hdWRpb19sYW5ndWFnZXNcIjpbXSxcImNoYW5uZWxfYXVkaW9fbGFuZ3VhZ2VzXCI6W10sXCJkdXJhdGlvbl90ZXh0XCI6XCI5OTlcIixcInZhbGlkX2Zvcl9hbGxfY291bnRyaWVzXCI6dHJ1ZSxcImFsbG93ZWRfcGxheWJhY2tfZHVyYXRpb25cIjo2LFwiY2F0ZWdvcnlcIjpcIlwifSxcInN1YnNjcmlwdGlvbl9zdGFydFwiOlwiMjAyMi0wMi0xNVQxNzo1NzoyMC40NDNaXCIsXCJzdWJzY3JpcHRpb25fZW5kXCI6XCIyMDIzLTAyLTE1VDIzOjU5OjU5WlwiLFwic3RhdGVcIjpcImFjdGl2YXRlZFwiLFwicmVjdXJyaW5nX2VuYWJsZWRcIjpmYWxzZSxcInBheW1lbnRfcHJvdmlkZXJcIjpcImNybVwiLFwiZnJlZV90cmlhbFwiOm51bGwsXCJjcmVhdGVfZGF0ZVwiOlwiMjAyMi0wMi0xNVQxNzo1NzoyMC40NDNaXCIsXCJpcF9hZGRyZXNzXCI6XCIxMDYuMjA4LjEyNy4xMzhcIixcImNvdW50cnlcIjpcIklOXCIsXCJyZWdpb25cIjpcIlRlbGFuZ2FuYVwiLFwiYWRkaXRpb25hbFwiOntcImFtb3VudFwiOjQ5OSxcInBheW1lbnRfdHhuX2lkXCI6XCJ6ZWU1LTcyOTg2Mzc0X2IxT0l4OWd2dENld2RhVHUtMVwiLFwicmVxdWVzdF9jYWxsX2Zyb21cIjpcIldlYmhvb2tcIixcInBheW1lbnRtb2RlXCI6XCJVUElcIixcInRyYW5zYWN0aW9uX2lkXCI6XCI3Mjk4NjM3NF9iMU9JeDlndnRDZXdkYVR1XCIsXCJkaXNjb3VudF9hbW91bnRcIjpcIjAuMDAwMFwiLFwiZnJlZV90cmlhbFwiOm51bGwsXCJyZWN1cnJpbmdfZW5hYmxlZFwiOmZhbHNlLFwib3JpZ2luYWxfdXNlcl9hZ2VudFwiOlwib2todHRwLzQuOS4xXCIsXCJzdWJzY3JpcHRpb25fdHlwZVwiOlwiU1VCU0NSSVBUSU9OXCJ9LFwiYWxsb3dlZF9iaWxsaW5nX2N5Y2xlc1wiOjAsXCJ1c2VkX2JpbGxpbmdfY3ljbGVzXCI6MH1dIiwic2NvcGUiOlsic3Vic2NyaXB0aW9uYXBpIiwidXNlcmFwaSIsIm9mZmxpbmVfYWNjZXNzIl0sImFtciI6WyJkZWxlZ2F0aW9uIl19.ewKkNidn56oUtn9VkzyHO8u_VtxMDn3633xsB5alHmD2ohR7jU4wZSC_-IIm4Z1K2w4LKyfWc06z1w3yYtiw_3agTjxK-ZQR9T-FS3PgeQAYXUxhNX_z2kBDfuvvOXlFKpf5Y6WURexoOhXbMGJMEYuohQbe4f3fh4PVhzNkmUeCxDEv1sdiymJSCMw1KhSwAkEmAojwUUYfSzfLilsoreNXs3VPJLphc171Gf_BkvEu4XU8kLaNt56Pw3wS59FhO9QgC6tHKGSLSufQcEu8njm4g4XhKiFRta_cwaJKrrfRt3RSRpUNcBOfOno_E9t1VbDBYWlZzrQBzD6g3GVx_w"   
}',
  CURLOPT_HTTPHEADER => array(
    'Content-Type: application/json'
  ),
));

$response = curl_exec($curl);

curl_close($curl);

$zx = json_decode($response, true);

$image= $zx["assetDetails"]['image_url'];
$img = str_replace('270x152', '1170x658', $image);
$title= $zx["assetDetails"]['title'];
$playit= $zx["keyOsDetails"]['video_token'];

header("Content-Type: application/json");
$errr= array("error" => "Put Here Only ZEE5 Proper URL ,  Invalid Input " );
$err =json_encode($errr);


$apii = array("title" => $title, "image" => $img,  "url" => $playit, "created_by" => "Avishkar Patil");

$api =json_encode($apii, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);

//header("Content-Type: application/json");
//echo $api;
header("Location: $playit"); //--> For Direct Play

  
?>
